#!/usr/bin/env python

import sys
import json
import os

args = sys.argv
args.pop(0)

with open('scripts.json') as json_file:
		scripts = json.load(json_file)
		for script in scripts:
			if len(args) and args[0] == script:
				scriptArgs = args
				scriptArgs.pop(0)
				scriptArgs = " ".join(scriptArgs)
				print("Running: ",scripts[script]+" "+scriptArgs)
				os.system(scripts[script]+" "+scriptArgs)
