name: Deno CI

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        deno: [0.32.0, 0.31.0]
    
    name: Deno ${{ matrix.deno }}
    steps:
    - uses: actions/checkout@v2
    - name: Deno Test
      uses: denolib/setup-deno@master
      with:
        deno-version: ${{ matrix.deno }}
    - run: deno ./test/index.ts
      env:
        CI: true

  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        deno: [0.32.0]
    
    name: Deno ${{ matrix.deno }}
    steps:
    - uses: actions/checkout@v2
    - name: Deno Build
      uses: denolib/setup-deno@master
      with:
        deno-version: ${{ matrix.deno }}
    - run: deno bundle ../src/index.ts ../dist/index.js
    - name: Upload Artifact
      uses: actions/upload-artifact@v1
      with:
        name: dist
        path: ./dist/index.js
      env:
        CI: true
